name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g. v1.3.5-blaxel.1)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 480
    env:
      TARGET: x86_64-unknown-linux-musl

    steps:
      - name: Checkout tag
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.tag }}
          submodules: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ env.TARGET }}

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y protobuf-compiler libclang-dev
          rustup target add ${{ env.TARGET }}
          cargo +stable install cargo-zigbuild
          sudo snap install zig --classic --beta

      - name: Build binaries
        run: |
          cargo zigbuild --release --bins --workspace --exclude hdfs --target ${{ env.TARGET }}

      - name: Build archive client(TAR)
        run: |
          binary_name="dragonfly-client"
          dirname="$binary_name-${{ inputs.tag }}-${{ env.TARGET }}"
          mkdir -p "$dirname"
          mv "target/${{ env.TARGET }}/release/dfget" "$dirname"
          mv "target/${{ env.TARGET }}/release/dfdaemon" "$dirname"
          mv "target/${{ env.TARGET }}/release/dfcache" "$dirname"
          mv "target/${{ env.TARGET }}/release/dfstore" "$dirname"
          mv "target/${{ env.TARGET }}/release/dfctl" "$dirname"
          mv "target/${{ env.TARGET }}/release/dfinit" "$dirname"
          mv CONTRIBUTING.md LICENSE README.md "$dirname"
          tar -czf "$dirname.tar.gz" "$dirname"
          echo "CLIENT_TAR_ASSET=$dirname.tar.gz" >> $GITHUB_ENV

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: release-${{ env.TARGET }}
          path: |
            ${{ env.CLIENT_TAR_ASSET }}

  release-github:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Download Release Artifacts
        uses: actions/download-artifact@v7
        with:
          path: releases
          pattern: release-*
          merge-multiple: true

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.tag }}
          artifacts: 'releases/*'
          generateReleaseNotes: true
          allowUpdates: true
          draft: true
